FROM  node:16-bullseye

MAINTAINER Luc Claustres <luc.claustres@kalisio.xyz>

COPY . /opt/feathers-distributed

WORKDIR /opt/feathers-distributed
RUN yarn install
WORKDIR /opt/feathers-distributed/example/service
RUN yarn install

EXPOSE 3031

CMD [ "npm", "start" ]
